/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TIG;

import TIG.scripts.compiler.Interpreter;

public class App {

    public static void main(String[] args) {
    	Interpreter interp = new Interpreter("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\TestScript1.cis", null);
    	interp.compile();
    	interp.interpret();
    }
}
