/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TIG;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import TIG.characterSheet.CharacterSheet;
import TIG.gui.CharacterSheetPane;
import TIG.scripts.compiler.Interpreter;
import TIG.utils.Def;
import TIG.utils.IO;
import TIG.utils.TestData;

public class App {
	
	private static final Logger LOG = LoggerFactory.getLogger(App.class);
	
	// For testing
	private static final String characterSavePath = TestData.testCharacter.getGeneralInfo().getCharacterName() + Def.characterFileExtension;

    public static void main(String[] args) {
    	LOG.debug("Application started");
    	//runGuiTest(args);
    	runCharacterTests();
    	//runIOTests();
    }
    
    @SuppressWarnings("unused")
    private static void runGuiTest(String[] args) {
    	CharacterSheetPane.main(args);
    }

    @SuppressWarnings("unused")
	private static void runCharacterTests() {
    	LOG.debug("Saving test data");
    	IO.saveCharacter(TestData.testCharacter, null);

    	CharacterSheet character = null;
    	try {
    		character = IO.loadCharacter(characterSavePath);
    	}catch(Exception e) {
    		e.printStackTrace();
    	}

    	LOG.debug("Loading and running interpreter on test script");
    	/*Interpreter interp = new Interpreter("res\\TestScript1.rpgs", character);
    	interp.compile();
    	interp.run();*/
    	character.getFeatures().getFeature("Strength").getScripts().getScript("test_script").run(character);

    	LOG.debug("Saving modified test data");
    	IO.saveCharacter(character, "PostScriptTestSave" + Def.characterFileExtension);
    }
    
    @SuppressWarnings("unused")
    private static void runIOTests() {
    	System.out.println(IO.getDirectoryPath("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System"));
    	System.out.println(IO.getDirectoryPath("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\"));
    	System.out.println(IO.getDirectoryPath("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\bogus\\dir\\"));
    	System.out.println(IO.getDirectoryPath("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\CFG2.txt"));
    	System.out.println(IO.getDirectoryPath("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\bogus\\dir\\CFG2.txt"));
    	System.out.println(IO.getDirectoryPath("Test.txt"));
    	System.out.println(IO.getDirectoryPath("characters\\Test.txt"));
    	System.out.println();
    	System.out.println(IO.getFileName("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System"));
    	System.out.println(IO.getFileName("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\"));
    	System.out.println(IO.getFileName("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\bogus\\dir"));
    	System.out.println(IO.getFileName("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\res\\CFG3.txt"));
    	System.out.println(IO.getFileName("D:\\Users\\Jacob\\Coding\\Java\\RPGIS\\RPG-Integrated-System\\ress\\bogus\\dir\\CFG12.txt"));
    	System.out.println(IO.getFileName("Test.txt"));
    	System.out.println(IO.getFileName("characters\\Test.txt"));
    	/* Requires changing IO.saveCharacter() to return the final path
    	System.out.println();
    	System.out.println(IO.saveCharacter(TestData.testCharacter, "testSave2.rpgc"));
    	System.out.println(IO.saveCharacter(TestData.testCharacter, "D:\\Users\\Jacob\\Documents"));
    	System.out.println(IO.saveCharacter(TestData.testCharacter, "D:\\Users\\Jacob\\Documents\\testSave2.rpgc"));
    	*/
    }
}
